name: stunt-extreme # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Stunt Drivers Extreme
summary: Perform daring stunts on crazy tracks.
description: Take control of high-speed vehicles and showcase breathtaking stunts in challenging obstacle courses.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  stunt-extreme:
    command: bin/stunt-extreme-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  stunt-extreme:
    plugin: dump
    source: .
    organize:
      stunt-extreme-bin: bin/
